version: '3'
project_name: tomiko_trade
services:
    nginx:
        restart: always
        build:
          context: ./nginx
          dockerfile: Dockerfile
        image: nginx:latest
        expose:
          - 8080
        ports:
          - 8080:8080
        volumes:
            - ./tomiko_trade/static:/static
            - ./tomiko_trade/media:/media
            - ./tomiko_trade/logs:/logs
            - ./nginx:/etc/nginx/conf.d
        depends_on:
            - python
            - client
    python:
        restart: always
        build:
            context: ./tomiko_trade/
            dockerfile: Dockerfile
        volumes:
            - ./tomiko_trade:/app
        expose:
          - 4000
        ports:
            - 4000:4000
    client:
        restart: always
        build:
            context: ./client
            dockerfile: Dockerfile
        volumes:
          - ./client:/client
        expose:
          - 8000
        ports:
          - 8000:8000

    postgres:
      image: postgres
      ports:
          - 5432:5432
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres_password
          - POSTGRES_DB=parking
      volumes:
          - ./tomiko_trade/database:/docker-entrypoint-initdb.d
