version: '3'
services:
    nginx:
        restart: always
        build:
          context: ./nginx
          dockerfile: Dockerfile
        image: nginx:latest
        expose:
          - 8080
        ports:
          - 8080:8080
        volumes:
            - ./nginx:/etc/nginx/conf.d
        depends_on:
            - python
            - client
    python:
        restart: always
        build:
            context: ./server/
            dockerfile: Dockerfile
        volumes:
            - ./server:/app
        expose:
          - 4000
        ports:
            - 4000:4000
        depends_on:
          postgres:
            condition: service_healthy

    client:
        restart: always
        build:
            context: ./client
            dockerfile: Dockerfile
        volumes:
          - ./client:/client
        expose:
          - 8000
        ports:
          - 8000:8000

    postgres:
      image: postgres
      ports:
          - 5432:5432
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres_password
          - POSTGRES_DB=parking
      volumes:
          - ./server/database:/docker-entrypoint-initdb.d
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5
