version: '3'

volumes:
    pgdata:
        driver: local
services:
    nginx:
        restart: always
        build:
          context: ./docker/nginx
          dockerfile: Dockerfile
        image: nginx:latest
        expose:
          - 8080
        ports:
          - 8080:8080
        volumes:
            - ./tomiko_trade/static:/static
            - ./tomiko_trade/media:/media
            - ./tomiko_trade/logs:/logs
            - ./docker/nginx:/etc/nginx/conf.d
        depends_on:
            - python
    python:
        restart: always
        build:
            context: .
            dockerfile: docker/python/Dockerfile
        volumes:
            - ./tomiko_trade:/tomiko_trade
        expose:
          - 8000
        ports:
            - 8000:8000
    postgres:
        image: postgres:9.3.22
        ports:
            - 5435:5435
        environment:
            POSTGRES_USER: username
            POSTGRES_PASSWORD: postgresql_password
            POSTGRES_DB: database_name
            PGDATA: /var/lib/postgresql/data
        volumes:
            - pgdata:/var/lib/postgresql/data
