# Generated by Django 5.1.4 on 2024-12-07 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=150)),
                ('brand', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('price', models.IntegerField()),
                ('transmission', models.CharField(max_length=50)),
                ('engine_volume', models.CharField(max_length=50)),
                ('drive', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('power_volume', models.CharField(max_length=50)),
                ('brand_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='parking.brand')),
            ],
        ),
    ]
