# Generated by Django 5.1.3 on 2024-12-07 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='brand',
            table='brands',
        ),
        migrations.AlterModelTable(
            name='car',
            table='cars',
        ),
    ]
